# Generated by Django 4.2.13 on 2025-07-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('mydc_ref', models.IntegerField()),
                ('otp', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=100)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('business_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('global_iqp', models.CharField(blank=True, max_length=100, null=True)),
                ('bo_pm', models.CharField(max_length=100)),
                ('bo_pl2', models.CharField(max_length=100)),
                ('bo_acqp_maturity', models.CharField(max_length=100)),
                ('bo_acqp_assessment_date', models.DateField(blank=True, null=True)),
                ('planned_deliverables', models.IntegerField()),
                ('otd', models.IntegerField()),
                ('otd_target', models.FloatField()),
                ('actual_otd_percent', models.FloatField()),
                ('right_first_time', models.IntegerField()),
                ('rft_target', models.FloatField()),
                ('actual_rft_percent', models.FloatField()),
                ('skill_compliance', models.FloatField()),
                ('csat_level', models.IntegerField()),
                ('csat_date', models.DateField(blank=True, null=True)),
                ('csat_service_mgmt', models.IntegerField()),
                ('csat_quality', models.IntegerField()),
                ('csat_autonomy', models.IntegerField()),
                ('csat_communication', models.IntegerField()),
                ('csat_flexibility', models.IntegerField()),
                ('csat_proactivity', models.IntegerField()),
                ('fte_count', models.FloatField()),
                ('attrition', models.IntegerField()),
                ('replaced_fte', models.IntegerField()),
                ('real_capacity_hours', models.FloatField()),
                ('time_sold_hours', models.FloatField()),
                ('turnover_engaged', models.FloatField()),
                ('cumulative_turnover_engaged', models.FloatField()),
                ('po_received', models.FloatField()),
                ('cumulative_po_received', models.FloatField()),
                ('current_dan', models.FloatField()),
                ('cumulative_dan', models.FloatField()),
                ('std_target_margin', models.FloatField()),
                ('std_forecasted_margin', models.FloatField()),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectKPISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('h1', models.FloatField()),
                ('target_h', models.FloatField()),
                ('htd', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_summaries', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFTESummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fte', models.IntegerField()),
                ('iqp1', models.IntegerField()),
                ('iqp2', models.IntegerField()),
                ('iqp3', models.IntegerField()),
                ('iqp4', models.IntegerField()),
                ('iqp5', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_summaries', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(choices=[('PMP', 'PMP'), ('Skill Matrix', 'Skill Matrix'), ('SLA', 'SLA'), ('Turtle Chart', 'Turtle Chart'), ('Other', 'Other')], max_length=50)),
                ('document_link', models.URLField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
        ),
    ]
